repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.5.1 # Get the latest from: https://github.com/asottile/add-trailing-comma
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-system
        name: "terraform-docs-root"
        args: ["markdown", "table", "--output-file", "./README.md", "--output-mode", "inject", "--lockfile=false", "."]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - '--args=--module'
          - '--args=--config=.tflint.hcl'
          - '--args=--enable-rule=terraform_comment_syntax'
          - '--args=--enable-rule=terraform_deprecated_index'
          - '--args=--enable-rule=terraform_deprecated_interpolation'
          - '--args=--enable-rule=terraform_documented_outputs'
          - '--args=--enable-rule=terraform_documented_variables'
          - '--args=--enable-rule=terraform_module_pinned_source'
          - '--args=--enable-rule=terraform_naming_convention'
          - '--args=--enable-rule=terraform_required_version'
          - '--args=--enable-rule=terraform_standard_module_structure'
          - '--args=--enable-rule=terraform_typed_variables'
          - '--args=--enable-rule=terraform_unused_declarations'
      - id: terraform_validate
